# Generated by Django 5.1.3 on 2024-12-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_university_alter_education_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=100, null=True)),
                ('text', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='about_me',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.TextField(default=None, null=True)),
                ('cv', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageinCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cv')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, max_length=200, null=True)),
                ('project_content', models.TextField(default=None, null=True)),
                ('cv', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Project_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default=None, max_length=500, null=True)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default=None, max_length=500, null=True)),
                ('cv', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cv')),
            ],
        ),
    ]
