# Generated by Django 5.1.3 on 2025-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_language_cv_about_me_education_text_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
