# Generated by Django 5.1.3 on 2025-01-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sociallink_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='display_name',
        ),
        migrations.CreateModel(
            name='Displayname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('social_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sociallink')),
            ],
        ),
    ]
