# Generated by Django 5.1.3 on 2025-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_student_password_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
