# Generated by Django 5.1.3 on 2025-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_company_company_name_alter_hr_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='link_job',
            field=models.TextField(),
        ),
    ]
